<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_TestSlow" Id="{8cd1133b-3477-41c9-9026-b27d8cb7f6d2}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_TestSlow
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	fbEvent: 			Tc3_Event.FB_Event;
	bVerbose:			BOOL;
	bInfo:				BOOL;
	bWarning:			BOOL;
	bError:				BOOL;
	bCritical:			BOOL;

END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbEvent();

// Demonstration of FB_Event usage with various log levels and argument types

IF bVerbose THEN
	fbEvent.P_Argument.M_AddINT(134052566194980000);
	fbEvent.P_Argument.M_AddSTRING('mm');
	fbEvent.M_Verbose('V message %s %s');
END_IF

IF bInfo THEN
	fbEvent.P_Argument.M_AddREAL(33.134581234, 3);
	fbEvent.P_Argument.M_AddSTRING('mm');
	fbEvent.M_Info('I message %s %s', 0);
END_IF

IF bWarning THEN
	fbEvent.M_Warning('W message', 0);
	fbEvent.M_Warning('B message', 475719253);
END_IF

IF bError THEN
	fbEvent.M_Error('E message', 475719235);
END_IF

IF bCritical THEN
	fbEvent.M_Error('Input %s is simulated', 849363082);
END_IF
]]></ST>
    </Implementation>
    <Property Name="P_Event" Id="{1b280b73-a5c7-4186-ac99-29403b5a1044}">
      <Declaration><![CDATA[PROPERTY PUBLIC P_Event : reference to FB_event]]></Declaration>
      <Get Name="Get" Id="{f7a9f415-12a5-443c-b0d8-84df15e2089b}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[P_Event ref= fbEvent;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>