<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_TestFast" Id="{ac478935-082b-4a26-8ace-9a48a4324c7d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_TestFast
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	fbEvent: 			Tc3_Event.FB_Event;
	bVerbose:			BOOL;
	bInfo:				BOOL;
	bWarning:			BOOL;
	bError:				BOOL;
	bCritical:			BOOL;

END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbEvent();

// Demonstration of FB_Event usage with various log levels and argument types

IF bVerbose THEN
	fbEvent.P_Argument.M_AddINT(134052566194980000);
	fbEvent.P_Argument.M_AddSTRING('mm');
	fbEvent.M_Verbose('V message %s %s');
END_IF

IF bInfo THEN
	fbEvent.P_Argument.M_AddREAL(33.134581234, 3);
	fbEvent.P_Argument.M_AddSTRING('mm');
	fbEvent.M_Info('I message %s %s', 828536003);
END_IF

IF bWarning THEN
	fbEvent.M_Warning('W message', 475719253);
	fbEvent.M_Warning('W message', 475719253);
END_IF

IF bError THEN
	fbEvent.M_Error('E message', 475719235);
END_IF

IF bCritical THEN
	fbEvent.M_Critical('C message', 475719233); ///839384782
	fbEvent.M_Critical('B message', 0); 
END_IF
]]></ST>
    </Implementation>
    <Property Name="P_Event" Id="{63fbb4c9-9e22-4943-b7c2-35f7dcebbab1}">
      <Declaration><![CDATA[PROPERTY PUBLIC P_Event : reference to FB_event]]></Declaration>
      <Get Name="Get" Id="{26df797a-6ac5-4d0e-a3a7-1cfc9121b495}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[P_Event ref= fbEvent;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>